name: DJICellularPhone
options:
  bundleIdPrefix: com.bibilabusensei
targets:
  DJICellularPhone:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources
      - path: Resources
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bibilabusensei.DJICellularPhone
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        MARKETING_VERSION: "0.2.0"
        CURRENT_PROJECT_VERSION: "2"
        INFOPLIST_KEY_CFBundleDisplayName: DJI 模块研究
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
schemes:
  DJICellularPhone:
    build:
      targets:
        DJICellularPhone: all
